{{- if .Values.fakeEventGenerator.enabled }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "falco.fullname" . }}-event-generator
  labels:
    app: {{ template "falco.fullname" . }}-event-generator
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas:  {{ .Values.fakeEventGenerator.replicas }}
  template:
    metadata:
      labels:
        app: {{ template "falco.fullname" . }}-event-generator
    spec:
      containers:
      - name: {{ template "falco.fullname" . }}-event-generator
        image: sysdig/falco-event-generator:latest
---
{{- end }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "falco.operator.fullname" .}}
  labels:
    app: {{ template "falco.operator.fullname" .}}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "falco.operator.fullname" .}}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args: []
      serviceAccountName: {{ template "falco.operator.fullname" .}}
