apiVersion: apps/v1
kind: Deployment
metadata:
  name: falco-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: falco-operator
  template:
    metadata:
      labels:
        name: falco-operator
    spec:
      serviceAccountName: falco-operator
      containers:
        - name: falco-operator
          image: mumoshu/falco-operator:v0.12.1
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - falco-operator
          imagePullPolicy: IfNotPresent
          env:
            - name: OPERATOR_NAME
              value: "falco-operator"
